### ISSUE TITLE
Trace segments no longer reported to statsd

### ISSUE THREAD

**Issue by magro** [kamon-io/Kamon#166]
After upgrading to the latest kamon snapshot 0.3.6-125bee567e0b18ea5ec10f3a1fe76409673011d9 trace segments don't seem to be reported to statsd (traces are reported fine). In my own trace subscriber I still get trace segments (we're still using this for logging), so they're actually there.

I verified that trace segments are not reported by checking the 'timers' via statsd admin interface (additionally to just looking in grafana).

**Comment by ivantopo** [comment]
Martin, thanks for mentioning this. The StatsD now subscribes to things available in the [configuration file] by adding the category and the patterns for that category. You just need to add `trace-segment = [ "**" ]` to the `kamon.statsd.subscriptions` key. 

Previously segments were part of the trace metrics but now they are a separate entity that has a tag named `trace` with the trace name as value. Sadly tags can not be reported to StatsD, but you will still get the segment names anyway :).

[configuration file]: https://github.com/kamon-io/Kamon/blob/master/kamon-statsd/src/main/resources/reference.conf#L22

**Comment by ivantopo** [comment]
Martin, we just published `0.3.6-75fc2c8f5a6c8c714363f69e3fb2c2c9f1486ae0` for Scala 2.10 and `0.3.6-0cb49a7cc94a7a2040b0a8ffdba2cff395a0c0e8` for Scala 2.11 with this fix included, please give it a try :).

**Comment by magro** [comment]
Unfortunately this doesn't fix it. Neither using the new version nor using the new version + setting subscriptions explicitely.

**Comment by ivantopo** [comment]
Martin, I did try it a few times and it certainly works. Maybe you are expecting them to be in the same place they were before! In previous Kamon versions all segments were metrics in the trace itself but now they are a separate entity with category `trace-segment`, so they should be, if using the default name generator, under `stats.timers.your_app.your_host.trace-segment.segment_name...`.

Please, take a look at that pattern and let us know if you can find them!

**Comment by magro** [comment]
Ah, you're right, segments are available under trace-segment.

The disadvantage of this is that segments are no longer related to their traces. E.g. if you have different routes/traces like a) "/search" and b) "/page" and in both cases a "database" sement is recorded, then in grafana on a panel for "/search" I'd like to show only those "database" segments that were recorded for "/search" traces. Previously this was possible because segments were appended to their traces (e.g. "trace.search.database"), now this relation is lost.

Did you change this intentionally or was this case just not considered?

**Comment by magro** [comment]
As a workaround we could name our segments $traceName + "." + $segmentName but this feels like a workaround...

**Comment by magro** [comment]
Shall I open another issue for this? If you say that segments should be named including the trace name if needed this is also ok for me. I just need to know if you will change anything or if I should.

**Comment by ivantopo** [comment]
Martin, the relationship between traces and segments remains and in fact I consider it to be enhanced. Previously the metric name for the segments inside of the trace metrics group had some sort of pattern that allowed you to infer that those were segments... now, the segments entity is different, but all `trace-segment` entities are guaranteed to have a tag named "trace" that points to the trace name under which the segments were recorded. 

That being said, the StatsD module definitely needs a better naming for segments as they are supposed to be always scoped to traces. I'm going to change the segments be under `app.host.trace.trace_name.segments.segment_name`, that way you can't get lost :).

**Comment by magro** [comment]
Sounds great! So I'll wait for that and don't change things on our side. If you give me a hint where things have to be changed I could also submit a pull request if you want.

**Comment by ivantopo** [comment]
Martin, 1f4e5e64619a359880413cc6baf2182f5609753b includes the fix. I'll publish snapshots later today!

**Comment by magro** [comment]
Awesome!

**Comment by ivantopo** [comment]
Martin, sorry that I forgot to publish the snapshots... I just did, version `0.3.6-ef43abf9b54ba70783eb645f020b87c18bb58cb4` and the same version works for Scala 2.10 and 2.11. Let us know how it works for you :).

**Comment by magro** [comment]
@ivantopo I just updated kamon to the version you mentioned, unfortunately I don't see "segments" after "trace.$trace_name"... I don't see trace-segments anymore now.

**Comment by ivantopo** [comment]
@magro are you super entirely sure? The category `trace-segments` won't be reported anymore, but right next to the `trace.$trace_name.elapsed-time` you should see `trace.$trace_name.segments` and all the correspondent segments should be there. I just tested again to be sure and I definitely see the segments, can you please confirm that you are looking at a trace that has segments?

**Comment by magro** [comment]
Weird, I just checked it with the statsd tcp admin interface and there I see the segments, but grafana somehow does not display them (also editing a metric manually and setting the path does not work).

**Comment by magro** [comment]
Found it: I had to drop the existing data (rm'ed the docker container), starting from scratch fixed it.

**Comment by ivantopo** [comment]
That's odd, but definitely not something on our side :), glad you figured it out!
